name: Ubuntu KVM + Tmate

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-24.04

    steps:
      - name: System Info
        run: |
          echo "===== CPU ====="
          lscpu
          echo
          echo "===== Memory ====="
          free -h
          echo
          echo "===== KVM Check ====="
          if [ -e /dev/kvm ]; then
            echo "KVM Available"
          else
            echo "KVM Not Available"
          fi
      - name: Install Python And Qemu
        run: |
          sudo apt install  software-properties-common -y && sudo add-apt-repository ppa:deadsnakes/ppa -y && sudo apt install python3.13 python3.13-full python3.13-venv -y
&& python3.13 --version && python3.13 -m pip install Flask Flask-Bcrypt Flask-SocketIO Flask-Sock requests psutil paramiko 

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y \
            qemu-kvm \
            libvirt-daemon-system \
            libvirt-clients \
            bridge-utils \
            cpu-checker \
            tmate qemu-system

      - name: Verify KVM
        run: |
          kvm-ok || true
          ls -la /dev/kvm || true

      - name: Start Tmate Session
        run: |
          tmate -F
